version: "3.9"

services:
  photobooth:
    build: .
    volumes:
      - ./:/app
      - /app/resources/css/
      - /app/resources/js/
      - /app/vendor/
      - /app/node_modules/
    ports:
      - "80:80"
      - "443:443"
